"""initial schema

Revision ID: b174ef3242cd
Revises: 
Create Date: 2026-09-02 15:30:49.712697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b174ef3242cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('trakt_id', sa.Integer(), nullable=True),
    sa.Column('trakt_slug', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_title', sa.String(length=300), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('poster_path', sa.String(length=200), nullable=True),
    sa.Column('backdrop_path', sa.String(length=200), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('tmdb_vote_average', sa.Float(), nullable=True),
    sa.Column('metadata_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_imdb_id'), ['imdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_tmdb_id'), ['tmdb_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_movies_trakt_id'), ['trakt_id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trakt_username', sa.String(length=120), nullable=True),
    sa.Column('joined_round', sa.Integer(), nullable=False),
    sa.Column('left_round', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('profile_path', sa.String(length=200), nullable=True),
    sa.Column('known_for_department', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_tmdb_id'), ['tmdb_id'], unique=True)

    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='roundstatus', native_enum=False), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('discussed_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rounds_number'), ['number'], unique=True)

    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('watches_added', sa.Integer(), nullable=False),
    sa.Column('ratings_added', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('CAST', 'CREW', name='creditkind', native_enum=False), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('job', sa.String(length=120), nullable=True),
    sa.Column('character', sa.String(length=300), nullable=True),
    sa.Column('billing_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'person_id', 'kind', 'job', 'character')
    )
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credits_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_job'), ['job'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_person_id'), ['person_id'], unique=False)

    op.create_table('movie_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'genre_id')
    )
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id')
    )
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_picks_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_picks_round_id'), ['round_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('rated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('TRAKT', 'MANUAL', name='recordsource', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id', 'movie_id')
    )
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ratings_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ratings_round_id'), ['round_id'], unique=False)

    op.create_table('round_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id')
    )
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('TRAKT', 'MANUAL', name='recordsource', native_enum=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id', 'movie_id')
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_round_id'), ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_round_id'))
        batch_op.drop_index(batch_op.f('ix_watches_participant_id'))
        batch_op.drop_index(batch_op.f('ix_watches_movie_id'))

    op.drop_table('watches')
    op.drop_table('round_participants')
    with op.batch_alter_table('ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ratings_round_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_participant_id'))
        batch_op.drop_index(batch_op.f('ix_ratings_movie_id'))

    op.drop_table('ratings')
    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_picks_round_id'))
        batch_op.drop_index(batch_op.f('ix_picks_participant_id'))
        batch_op.drop_index(batch_op.f('ix_picks_movie_id'))

    op.drop_table('picks')
    op.drop_table('movie_genres')
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credits_person_id'))
        batch_op.drop_index(batch_op.f('ix_credits_movie_id'))
        batch_op.drop_index(batch_op.f('ix_credits_kind'))
        batch_op.drop_index(batch_op.f('ix_credits_job'))
        batch_op.drop_index(batch_op.f('ix_credits_department'))

    op.drop_table('credits')
    op.drop_table('sync_logs')
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rounds_number'))

    op.drop_table('rounds')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_tmdb_id'))

    op.drop_table('people')
    op.drop_table('participants')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_trakt_id'))
        batch_op.drop_index(batch_op.f('ix_movies_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_movies_imdb_id'))

    op.drop_table('movies')
    op.drop_table('genres')
    # ### end Alembic commands ###
