"""physical media shelf

Revision ID: ff2338c9185a
Revises: b174ef3242cd
Create Date: 2026-09-09 09:54:44.597363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2338c9185a'
down_revision: Union[str, None] = 'b174ef3242cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('UHD_4K', 'BLU_RAY', 'DVD', name='mediaformat', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'format')
    )
    with op.batch_alter_table('physical_copies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_physical_copies_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_copies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_physical_copies_movie_id'))

    op.drop_table('physical_copies')
    # ### end Alembic commands ###
